# ==========================================
# 1. \uB370\uC774\uD130\uBCA0\uC774\uC2A4(DB) \uC5F0\uACB0 \uC124\uC815 (MySQL/MariaDB)
# ==========================================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/dbstudy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=1111

# ==========================================
# 2. JSP \uD654\uBA74(View) \uACBD\uB85C \uC124\uC815
# ==========================================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ==========================================
# 3. \uBA54\uC77C \uC804\uC1A1 \uC124\uC815 (\uB124\uC774\uBC84 SMTP)
# ==========================================
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=aaju-4753@naver.com
spring.mail.password=KXX3J1XQB5MN
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com

# ==========================================
# 4. \uB9C8\uC774\uBC14\uD2F0\uC2A4 (MyBatis) \uACBD\uB85C \uC124\uC815
# ==========================================
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=org.study.mypractice01.vo
